My portfolio: mobile version skeleton
abiodunraheem/Portfolio pull request #2
Opened 2022-02-18 19:40 UTC by abiodunraheem

Understand how to parse a Figma design to create a UI.
Flexbox to place elements in the page.
Build a personal portfolio site.
Use images and backgrounds to enhance the look of the website.

2022-02-18 20:41 UTC, RolandM99 requested changes
Hi  @abiodunraheem , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

### To highlight 💯 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 
- Descriptive PR ✔️  

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Rolandm99 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 20:41 UTC, RolandM99 commented on index.html
> +            <h2>My Recent Works</h2>
- [ ] The container of the works section should be a `<section>` tag. Please, Kindly wrap your code from line 47 to 162 with  `<section>...</section>` tag

2022-02-18 20:41 UTC, RolandM99 commented on style.css
> +  margin-top: 12px;
- [x] Please,  Add the button styling (Hover, enable, Active, Pressed ) referencing to the Figma template.
### Figma design :  
![image](https://user-images.githubusercontent.com/71874425/153439044-5425e7da-e7cf-4629-924e-c975dc567c9e.png)

2022-02-18 20:41 UTC, RolandM99 commented on index.html
> +                    <div class="background-image"></div>
- [ ] The section should have the margins(top, left, right, bottom) defined in the Figma design. Kindly, make sure that they are similar. 

**Here is your implementation**: 
![image](https://user-images.githubusercontent.com/71874425/154756181-1f59a324-67b5-444a-b729-5eb657c7b643.png)
**Figma template**:

![image](https://user-images.githubusercontent.com/71874425/154756378-ff7e9d2b-61f2-4989-9ff9-0149d587936b.png)

2022-02-18 20:41 UTC, RolandM99 commented on index.html
> +                    <h2>About me</h2>
- [ ] The container of the about page should be a `section` tag. Kindly wrap your code from line 164 to 200 with `<section>...</section>` tag.

2022-02-18 20:41 UTC, RolandM99 commented on index.html
> +
- [ ] Please, use `ul` tag instead of `div` for the list of technologies used and each of them a `li` tag instead of `p`.
- Example:
```
<ul>
   <li></li>
   <li></li>
   <li></li>
</ul>

2022-02-19 11:42 UTC, prolajumokeoni commented on style.css
> +  margin-top: 12px;
@abiodunraheem Good job implementing required changes

2022-02-19 11:47 UTC, prolajumokeoni commented on index.html
> +                    <h2>About me</h2>
- [ ] Kindly change div tag of class "footer-content" of this section to section tag, this makes your website semantic and makes your code easier to read by you and screen readers  👍🏿

2022-02-19 11:56 UTC, prolajumokeoni requested changes
Hi @abiodunraheem 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights
 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
_check inline comments_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-19 11:56 UTC, prolajumokeoni commented on style.css
> +  border: 1px solid #8993a4;
##OPTIONAL

- [ ] Kindly change border outline to   `border: 1px solid #ff6b00;` so it looks like the original design 👍🏿

2022-02-19 11:56 UTC, prolajumokeoni commented on style.css
> +  border: 1px solid #8993a4;
##OPTIONAL

- [ ] Kindly change border outline to   `border: 1px solid #ff6b00;` so it looks like the original design 👍🏿

2022-02-19 12:12 UTC, abiodunraheem commented
@prolajumokeoni Please review the changes I've made before I submit. Am having just one more attempt. Thank you.

2022-02-19 13:51 UTC, ReshyResh approved these changes
# Hi @abiodunraheem , 

### Good job addressing the changes requested by the previous reviewers!
#### Your project is complete!  There is nothing else to say other than... it's time to merge it!
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

----

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-02-19 16:43 UTC, merged